# Dihya Backend Assets – Modèle IA : Métadonnées TOML (exemple, multilingue, RGPD, production-ready)
model_name = "mixtral-8x7b"
version = "1.0.0"
type = "binaire"
hash_sha256 = "..."
license = "open source"

[description]
fr = "Modèle IA open source Mixtral 8x7B, optimisé pour la génération de texte multilingue."
en = "Open source AI model Mixtral 8x7B, optimized for multilingual text generation."
ar = "نموذج ذكاء اصطناعي مفتوح المصدر Mixtral 8x7B، مُحسَّن لتوليد النصوص متعددة اللغات."
kab = "Amuddir IA Mixtral 8x7B, yellan d open source, yebnan i usenfel n uḍris amaynut."

[rgpd]
personal_data = false
anonymization = true

author = "Equipe Dihya"
last_update = "2025-05-22T10:00:00Z"
