openapi: 3.0.0
info:
  title: API Services à la personne
  version: 1.0.0
paths:
  /services_personne/:
    get:
      summary: Liste des ressources Services à la personne
      responses:
        '200':
          description: Succès