openapi: 3.0.0
info:
  title: API Construction
  version: 1.0.0
paths:
  /construction/:
    get:
      summary: Liste des ressources Construction
      responses:
        '200':
          description: Succès