openapi: 3.0.0
info:
  title: API Banque/Finance
  version: 1.0.0
paths:
  /banque_finance/:
    get:
      summary: Liste des ressources Banque/Finance
      responses:
        '200':
          description: Succès