openapi: 3.0.0
info:
  title: API Environnement
  version: 1.0.0
paths:
  /environnement/:
    get:
      summary: Liste des ressources Environnement
      responses:
        '200':
          description: Succès