# Exemple de pipeline CI/CD pour valider les assets de sécurité
name: Validate Security Assets

on:
  push:
    paths:
      - 'blueprints/blockchain/assets/images/security/**'
      - 'blueprints/blockchain/assets/scripts/**'
  pull_request:
    paths:
      - 'blueprints/blockchain/assets/images/security/**'
      - 'blueprints/blockchain/assets/scripts/**'

jobs:
  validate-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Valider les assets
        run: |
          cd blueprints/blockchain/assets/scripts
          chmod +x validate_assets.sh
          ./validate_assets.sh
