name: Marketplace Frontend CI

on:
  push:
    paths:
      - 'blueprints/frontend/src/marketplace/**'
  pull_request:
    paths:
      - 'blueprints/frontend/src/marketplace/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd blueprints/frontend/src/marketplace
          npm install || true
      - name: Lint & Test
        run: |
          cd blueprints/frontend/src/marketplace
          npm run lint || echo 'No linter'
          npm test || echo 'No tests'
      - name: Audit
        run: |
          echo 'Audit automatique du code (Lead Dev)'
