openapi: 3.0.0
info:
  title: API Hôtellerie
  version: 1.0.0
paths:
  /hotellerie/:
    get:
      summary: Liste des ressources Hôtellerie
      responses:
        '200':
          description: Succès