# Exemple ultra avancé : config YAML (audit, RGPD, sécurité, accessibilité, CI/CD, monitoring)
app:
  name: dihya-ultra
  env: production
  audit_log: true
  rgpd:
    consent_required: true
    anonymisation: true
    export_enabled: true
  i18n:
    default_lang: fr
    supported_langs:
      - fr
      - en
      - ar
      - tzm
      - de
      - zh
      - ja
      - ko
      - nl
      - he
      - fa
      - hi
      - es
  security:
    cors: true
    waf: true
    jwt: true
    rate_limit: 1000
    ddos_protection: true
  accessibility:
    enabled: true
    rgaa: true
    wcag: true
  monitoring:
    enabled: true
    provider: prometheus
