# config_example.toml – Exemple ultra avancé (audit, RGPD, sécurité, accessibilité, CI/CD, monitoring)
[app]
name = "dihya-ultra"
env = "production"
audit_log = true

[app.rgpd]
consent_required = true
anonymisation = true
export_enabled = true

[app.i18n]
default_lang = "fr"
supported_langs = ["fr", "en", "ar", "tzm", "de", "zh", "ja", "ko", "nl", "he", "fa", "hi", "es"]

[app.security]
cors = true
waf = true
jwt = true
rate_limit = 1000
ddos_protection = true

[app.accessibility]
enabled = true
rgaa = true
wcag = true

[app.monitoring]
enabled = true
provider = "prometheus"
