# Exemple ultra avancé : docker-compose (audit, RGPD, sécurité, accessibilité, CI/CD)
version: '3.9'
services:
  dihya-backend:
    build: ../..
    environment:
      - APP_ENV=production
      - AUDIT_LOG_ENABLED=true
      - RGPD_CONSENT_REQUIRED=true
    ports:
      - "8000:8000"
    volumes:
      - ../../:/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
