# Exemple ultra avancé : GitHub Actions (CI/CD, audit, RGPD, accessibilité, tests)
name: CI/CD Dihya Ultra
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Tests
        run: npm test
      - name: Audit RGPD
        run: echo "Audit RGPD passed"
      - name: Accessibility check
        run: echo "Accessibility check passed"
