openapi: 3.0.0
info:
  title: API Restauration
  version: 1.0.0
paths:
  /restauration/:
    get:
      summary: Liste des ressources Restauration
      responses:
        '200':
          description: Succès