openapi: 3.0.0
info:
  title: API Immobilier
  version: 1.0.0
paths:
  /immobilier/:
    get:
      summary: Liste des ressources Immobilier
      responses:
        '200':
          description: Succès