# prometheus_a_i.yml
global:
  scrape_interval: 15s  # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'a_i_business_module'
    metrics_path: '/metrics'  # Default metrics path
    static_configs:
      - targets: ['a_i_instance:port']  # Replace with the actual host and port where the module exposes metrics

    # Si l'authentification est nécessaire pour accéder aux métriques
    # basic_auth:
    #   username: 'user'
    #   password: 'password'

    # Si le module expose des métriques via HTTPS et nécessite un certificat client
    # tls_config:
    #   ca_file: '/path/to/ca_file'
    #   cert_file: '/path/to/cert_file'
    #   key_file: '/path/to/key_file'
    #   insecure_skip_verify: false

    # Si le module est derrière un service discovery ou un orchestrateur comme Kubernetes
    # kubernetes_sd_configs:
    # - role: pod
    #   namespaces:
    #     names:
    #       - a_i_namespace
