openapi: 3.0.0
info:
  title: API Administration Publique
  version: 1.0.0
paths:
  /administration_publique/:
    get:
      summary: Liste des ressources Administration Publique
      responses:
        '200':
          description: Succès