# Exemple ultra avancé : GitHub Actions CI/CD (audit, RGPD, accessibilité, tests, sécurité)
name: CI/CD Dihya Ultra Avancé
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Lint
        run: |
          flake8 backend/ --max-line-length=120
      - name: Tests
        run: |
          pytest --tb=short -v
      - name: Audit RGPD
        run: |
          python scripts/audit_rgpd.py
      - name: Accessibility check
        run: |
          python scripts/accessibility_check.py
