# Exemple Kubernetes ultra avancé (audit, RGPD, sécurité, accessibilité, CI/CD, monitoring)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dihya-backend
  labels:
    app: dihya
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dihya
  template:
    metadata:
      labels:
        app: dihya
    spec:
      containers:
      - name: dihya-backend
        image: dihya/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: AUDIT_LOG_ENABLED
          value: "true"
        - name: RGPD_CONSENT_REQUIRED
          value: "true"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
