# CI/CD pour E-commerce
name: CI_ecommerce
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Installer dépendances
        run: |
          pip install -r requirements.txt
      - name: Lancer les tests
        run: |
          pytest