# readonly.toml – Configuration lecture seule (Dihya Backend)
[app]
name = "Dihya Backend"
env = "readonly"

[security]
cors_enabled = true
csrf_enabled = true

[rgpd]
data_retention_days = 180
anonymize_on_delete = false
export_format = "csv"
user_data_access = false
user_data_portability = false
user_data_deletion = false

[logging]
level = "INFO"
format = "%(asctime)s %(levelname)s %(message)s"
