# rgpd_strict.toml – Configuration RGPD stricte (Dihya Backend)
[app]
name = "Dihya Backend"
env = "prod"

[security]
cors_enabled = false
csrf_enabled = true

[rgpd]
data_retention_days = 7
anonymize_on_delete = true
export_format = "json"
user_data_access = true
user_data_portability = true
user_data_deletion = true

[logging]
level = "WARNING"
format = "%(asctime)s %(levelname)s %(message)s"
