openapi: 3.0.0
info:
  title: API Blockchain
  version: 1.0.0
paths:
  /blockchain/:
    get:
      summary: Liste des ressources Blockchain
      responses:
        '200':
          description: Succès