name: Dihya CI/CD Ultra Avancé

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
      - name: Lint
        run: |
          flake8 .
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings
      - name: Build Docker image
        run: |
          docker build -t dihya:latest .
      - name: Deploy (K8s/Local fallback)
        run: |
          echo "Déploiement automatisé (K8s/Local fallback)"
      - name: SEO/Accessibility/Compliance checks
        run: |
          echo "Vérification SEO, accessibilité, conformité RGPD, audit"
