openapi: 3.0.0
info:
  title: API Agriculture
  version: 1.0.0
paths:
  /agriculture/:
    get:
      summary: Liste des ressources Agriculture
      responses:
        '200':
          description: Succès